// Required data for the shoe

export const brands = {
  "La Sportiva": {
    logoImage: "./assets/sportiva/sportiva.webp",
    models: [
      { name: "Solution", image: "/assets/sportiva/katana.jpg" },
      { name: "Genius", image: "/assets/sportiva/katana.jpg" },
      { name: "Futura", image: "/assets/sportiva/katana.jpg" },
      { name: "Skwama", image: "/assets/sportiva/katana.jpg" },
      { name: "Testarrosa", image: "/assets/sportiva/katana.jpg" },
      { name: "Otaki", image: "/assets/sportiva/katana.jpg" },
      { name: "Kataki", image: "/assets/sportiva/katana.jpg" },
      { name: "Miura Vs", image: "/assets/sportiva/katana.jpg" },
      { name: "Miura", image: "/assets/sportiva/katana.jpg" },
      { name: "Katana Laces", image: "/assets/sportiva/katana.jpg" },
      { name: "Tc Pro", image: "/assets/sportiva/katana.jpg" },
      { name: "Katana", image: "/assets/sportiva/katana.jpg" },
      { name: "Theory", image: "/assets/sportiva/katana.jpg" },
    ],
  },
  Scarpa: {
    logoImage: "/assets/scarpa/scarpa.jpg",
    models: [
      { name: "Drago", image: "/assets/scarpa/instinct.avif" },
      { name: "Furia", image: "/assets/scarpa/instinct.avif" },
      { name: "Boostic", image: "/assets/scarpa/instinct.avif" },
      { name: "Booster", image: "/assets/scarpa/instinct.avif" },
      { name: "Instinc", image: "/assets/scarpa/instinct.avif" },
      { name: "Vapor", image: "/assets/scarpa/instinct.avif" },
      { name: "Maestro", image: "/assets/scarpa/instinct.avif" },
      { name: "Chimera", image: "/assets/scarpa/instinct.avif" },
    ],
  },
  Tenaya: {
    logoImage: "/assets/tenaya/tenaya.webp",
    models: [
      { name: "Oasi", image: "/assets/tenaya/oasi.jpg" },
      { name: "Oasi Lv", image: "/assets/tenaya/oasi-lv.jpg" },
      { name: "Iati", image: "/assets/tenaya/iati.jpg" },
      { name: "Tarifa", image: "/assets/tenaya/tarifa.jpg" },
      { name: "Mundaka", image: "/assets/tenaya/mundaka.jpg" },
      { name: "Indalo", image: "/assets/tenaya/indalo.png" },
      { name: "Mastia", image: "/assets/tenaya/mastia.jpg" },
      { name: "Ra", image: "/assets/tenaya/ra.jpg" },
      { name: "Ra Woman", image: "/assets/tenaya/ra-woman.jpg" },
      { name: "Inti", image: "/assets/tenaya/inti.jpg" },
      { name: "Masai", image: "/assets/tenaya/masai.jpg" },
      { name: "Tanta", image: "/assets/tenaya/tanta.jpg" },
    ],
  },
};

export const comfortOptions = [
  "Beginners",
  "Prolonged Use",
  "Comfort Fit",
  "Tighter Fit",
];

export const sizeTypes = ["UK", "USM", "USW", "EU", "CM"];

export const sizes = {
  UK: [
    "1",
    "1 ½",
    "2",
    "2 ½",
    "3",
    "3 ½",
    "4",
    "4 ½",
    "5",
    "5 ½",
    "6",
    "6 ½",
    "7",
    "7 ½",
    "8",
    "8 ½",
    "9",
    "9 ½",
    "10",
    "10 ½",
    "11",
    "11 ½",
    "12",
    "12 ½",
    "13",
    "13 ½",
    "14",
  ],
  USM: [
    "2",
    "2 ½",
    "3",
    "3 ½",
    "4",
    "4 ½",
    "5",
    "5 ½",
    "6",
    "6 ½",
    "7",
    "7 ½",
    "8",
    "8 ½",
    "9",
    "9 ½",
    "10",
    "10 ½",
    "11",
    "11 ½",
    "12",
    "12 ½",
    "13",
    "13 ½",
    "14",
    "14 ½",
    "15",
  ],
  USW: [
    "3",
    "3 ½",
    "4",
    "4 ½",
    "5",
    "5 ½",
    "6",
    "6 ½",
    "7",
    "7 ½",
    "8",
    "8 ½",
    "9",
    "9 ½",
    "10",
    "10 ½",
    "11",
    "11 ½",
    "12",
    "12 ½",
    "13",
    "13 ½",
    "14",
    "14 ½",
  ],
  EU: [
    "33.0",
    "33.6",
    "34.3",
    "34.9",
    "35.6",
    "36.2",
    "36.8",
    "37.5",
    "38.1",
    "38.8",
    "39.4",
    "40.0",
    "40.7",
    "41.4",
    "42.0",
    "42.6",
    "43.2",
    "43.9",
    "44.5",
    "45.2",
    "45.8",
    "46.4",
    "47.1",
    "47.7",
    "48.4",
    "49.0",
    "49.6",
  ],
  CM: [
    "20.2",
    "20.6",
    "21.0",
    "21.4",
    "21.8",
    "22.3",
    "22.7",
    "23.1",
    "23.5",
    "24.0",
    "24.4",
    "24.8",
    "25.2",
    "25.6",
    "26.1",
    "26.5",
    "26.9",
    "27.3",
    "27.8",
    "28.2",
    "28.6",
    "29.0",
    "29.5",
    "29.9",
    "30.3",
    "30.7",
    "31.1",
  ],
};
